import type {
  Indicador,
  Comercial,
  Admin,
  Plano,
  Indicacao,
  Lead,
  Pagamento,
  Historico,
  DashboardIndicador,
  DashboardComercial,
  DashboardAdmin,
} from './types'

// Planos
export const planos: Plano[] = [
  { id: '1', nome: 'Tanto 100', velocidade: '100 Mbps', preco: 79.90, descricao: 'Ideal para uso básico', ativo: true },
  { id: '2', nome: 'Tanto 200', velocidade: '200 Mbps', preco: 99.90, descricao: 'Para famílias pequenas', ativo: true },
  { id: '3', nome: 'Tanto 400', velocidade: '400 Mbps', preco: 129.90, descricao: 'Para home office', ativo: true },
  { id: '4', nome: 'Tanto 600', velocidade: '600 Mbps', preco: 159.90, descricao: 'Para gamers', ativo: true },
  { id: '5', nome: 'Tanto Giga', velocidade: '1 Gbps', preco: 199.90, descricao: 'Máxima velocidade', ativo: true },
]

// Indicadores
export const indicadores: Indicador[] = [
  {
    id: 'ind-1',
    nome: 'Maria Silva',
    email: 'maria.silva@email.com',
    telefone: '(11) 99999-1111',
    role: 'indicador',
    chavePix: '123.456.789-00',
    tipoChavePix: 'cpf',
    totalIndicacoes: 25,
    indicacoesAprovadas: 18,
    totalRecebido: 1798.20,
    saldoDisponivel: 299.70,
    saldoDesconto: 99.90,
    createdAt: new Date('2024-01-15'),
  },
  {
    id: 'ind-2',
    nome: 'João Santos',
    email: 'joao.santos@email.com',
    telefone: '(11) 99999-2222',
    role: 'indicador',
    chavePix: 'joao.santos@email.com',
    tipoChavePix: 'email',
    totalIndicacoes: 42,
    indicacoesAprovadas: 35,
    totalRecebido: 3497.50,
    saldoDisponivel: 459.60,
    saldoDesconto: 0,
    createdAt: new Date('2023-11-20'),
  },
  {
    id: 'ind-3',
    nome: 'Ana Oliveira',
    email: 'ana.oliveira@email.com',
    telefone: '(11) 99999-3333',
    role: 'indicador',
    chavePix: '(11) 99999-3333',
    tipoChavePix: 'telefone',
    totalIndicacoes: 15,
    indicacoesAprovadas: 10,
    totalRecebido: 999.00,
    saldoDisponivel: 129.90,
    saldoDesconto: 199.80,
    createdAt: new Date('2024-02-10'),
  },
  {
    id: 'ind-4',
    nome: 'Carlos Mendes',
    email: 'carlos.mendes@email.com',
    telefone: '(11) 99999-4444',
    role: 'indicador',
    chavePix: 'abc123def456',
    tipoChavePix: 'aleatoria',
    totalIndicacoes: 8,
    indicacoesAprovadas: 5,
    totalRecebido: 499.50,
    saldoDisponivel: 79.90,
    saldoDesconto: 0,
    createdAt: new Date('2024-03-05'),
  },
  {
    id: 'ind-5',
    nome: 'Fernanda Lima',
    email: 'fernanda.lima@email.com',
    telefone: '(11) 99999-5555',
    role: 'indicador',
    chavePix: '98.765.432/0001-10',
    tipoChavePix: 'cnpj',
    totalIndicacoes: 67,
    indicacoesAprovadas: 58,
    totalRecebido: 5795.80,
    saldoDisponivel: 859.30,
    saldoDesconto: 129.90,
    createdAt: new Date('2023-08-12'),
  },
]

// Comerciais
export const comerciais: Comercial[] = [
  {
    id: 'com-1',
    nome: 'Roberto Alves',
    email: 'roberto.alves@tantotelecom.com.br',
    telefone: '(11) 98888-1111',
    role: 'comercial',
    disponibilidade: 'disponivel',
    leadsAtivos: 12,
    vendasRealizadas: 87,
    tempoMedioPrimeiroContato: 8,
    createdAt: new Date('2023-06-01'),
  },
  {
    id: 'com-2',
    nome: 'Patricia Costa',
    email: 'patricia.costa@tantotelecom.com.br',
    telefone: '(11) 98888-2222',
    role: 'comercial',
    disponibilidade: 'em_pausa',
    leadsAtivos: 8,
    vendasRealizadas: 112,
    tempoMedioPrimeiroContato: 5,
    createdAt: new Date('2023-03-15'),
  },
  {
    id: 'com-3',
    nome: 'Lucas Ferreira',
    email: 'lucas.ferreira@tantotelecom.com.br',
    telefone: '(11) 98888-3333',
    role: 'comercial',
    disponibilidade: 'disponivel',
    leadsAtivos: 15,
    vendasRealizadas: 65,
    tempoMedioPrimeiroContato: 12,
    createdAt: new Date('2023-09-20'),
  },
  {
    id: 'com-4',
    nome: 'Juliana Rocha',
    email: 'juliana.rocha@tantotelecom.com.br',
    telefone: '(11) 98888-4444',
    role: 'comercial',
    disponibilidade: 'offline',
    leadsAtivos: 0,
    vendasRealizadas: 94,
    tempoMedioPrimeiroContato: 7,
    createdAt: new Date('2023-05-10'),
  },
]

// Admins
export const admins: Admin[] = [
  {
    id: 'adm-1',
    nome: 'Marcos Diretor',
    email: 'marcos.diretor@tantotelecom.com.br',
    telefone: '(11) 97777-1111',
    role: 'admin_master',
    createdAt: new Date('2022-01-01'),
  },
  {
    id: 'adm-2',
    nome: 'Carla Financeiro',
    email: 'carla.financeiro@tantotelecom.com.br',
    telefone: '(11) 97777-2222',
    role: 'admin_financeiro',
    createdAt: new Date('2022-06-15'),
  },
  {
    id: 'adm-3',
    nome: 'Pedro Consulta',
    email: 'pedro.consulta@tantotelecom.com.br',
    telefone: '(11) 97777-3333',
    role: 'admin_consulta',
    createdAt: new Date('2023-01-10'),
  },
]

// Indicações
export const indicacoes: Indicacao[] = [
  {
    id: 'ind-001',
    indicadorId: 'ind-1',
    indicador: indicadores[0],
    nomeIndicado: 'Pedro Almeida',
    telefoneIndicado: '(11) 91111-0001',
    emailIndicado: 'pedro.almeida@email.com',
    planoId: '3',
    plano: planos[2],
    tipoRecompensa: 'pix',
    valorRecompensa: 129.90,
    status: 'aprovada',
    comercialId: 'com-1',
    comercial: comerciais[0],
    createdAt: new Date('2024-03-10'),
    updatedAt: new Date('2024-03-25'),
    primeiraFaturaPaga: true,
    dataAprovacao: new Date('2024-03-25'),
  },
  {
    id: 'ind-002',
    indicadorId: 'ind-1',
    indicador: indicadores[0],
    nomeIndicado: 'Lucia Martins',
    telefoneIndicado: '(11) 91111-0002',
    planoId: '2',
    plano: planos[1],
    tipoRecompensa: 'desconto_fatura',
    valorRecompensa: 99.90,
    status: 'em_andamento',
    comercialId: 'com-2',
    comercial: comerciais[1],
    createdAt: new Date('2024-04-05'),
    updatedAt: new Date('2024-04-10'),
  },
  {
    id: 'ind-003',
    indicadorId: 'ind-2',
    indicador: indicadores[1],
    nomeIndicado: 'Ricardo Souza',
    telefoneIndicado: '(11) 91111-0003',
    emailIndicado: 'ricardo.souza@email.com',
    planoId: '5',
    plano: planos[4],
    tipoRecompensa: 'pix',
    valorRecompensa: 199.90,
    status: 'pendente',
    createdAt: new Date('2024-04-20'),
    updatedAt: new Date('2024-04-20'),
  },
  {
    id: 'ind-004',
    indicadorId: 'ind-2',
    indicador: indicadores[1],
    nomeIndicado: 'Camila Pereira',
    telefoneIndicado: '(11) 91111-0004',
    planoId: '4',
    plano: planos[3],
    tipoRecompensa: 'pix',
    valorRecompensa: 159.90,
    status: 'aprovada',
    comercialId: 'com-1',
    comercial: comerciais[0],
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-03-20'),
    primeiraFaturaPaga: true,
    dataAprovacao: new Date('2024-03-20'),
  },
  {
    id: 'ind-005',
    indicadorId: 'ind-3',
    indicador: indicadores[2],
    nomeIndicado: 'Bruno Castro',
    telefoneIndicado: '(11) 91111-0005',
    planoId: '1',
    plano: planos[0],
    tipoRecompensa: 'desconto_fatura',
    valorRecompensa: 79.90,
    status: 'recusada',
    comercialId: 'com-3',
    comercial: comerciais[2],
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2024-03-01'),
  },
  {
    id: 'ind-006',
    indicadorId: 'ind-5',
    indicador: indicadores[4],
    nomeIndicado: 'Tatiana Gomes',
    telefoneIndicado: '(11) 91111-0006',
    emailIndicado: 'tatiana.gomes@email.com',
    planoId: '3',
    plano: planos[2],
    tipoRecompensa: 'pix',
    valorRecompensa: 129.90,
    status: 'em_andamento',
    comercialId: 'com-1',
    comercial: comerciais[0],
    createdAt: new Date('2024-04-18'),
    updatedAt: new Date('2024-04-22'),
  },
  {
    id: 'ind-007',
    indicadorId: 'ind-5',
    indicador: indicadores[4],
    nomeIndicado: 'Marcos Vieira',
    telefoneIndicado: '(11) 91111-0007',
    planoId: '2',
    plano: planos[1],
    tipoRecompensa: 'pix',
    valorRecompensa: 99.90,
    status: 'paga',
    comercialId: 'com-2',
    comercial: comerciais[1],
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-03-15'),
    primeiraFaturaPaga: true,
    dataAprovacao: new Date('2024-02-28'),
  },
]

// Leads
export const leads: Lead[] = [
  {
    id: 'lead-001',
    indicacaoId: 'ind-001',
    indicacao: indicacoes[0],
    comercialId: 'com-1',
    comercial: comerciais[0],
    status: 'vendido',
    primeiroContato: new Date('2024-03-10T10:30:00'),
    ultimoContato: new Date('2024-03-20T15:00:00'),
    observacoes: ['Cliente interessado', 'Agendada visita técnica', 'Instalação realizada com sucesso'],
    createdAt: new Date('2024-03-10'),
    updatedAt: new Date('2024-03-25'),
  },
  {
    id: 'lead-002',
    indicacaoId: 'ind-002',
    indicacao: indicacoes[1],
    comercialId: 'com-2',
    comercial: comerciais[1],
    status: 'em_negociacao',
    primeiroContato: new Date('2024-04-05T14:00:00'),
    ultimoContato: new Date('2024-04-10T11:30:00'),
    retornoAgendado: new Date('2024-04-25T10:00:00'),
    observacoes: ['Cliente pediu mais informações', 'Enviado comparativo de planos'],
    createdAt: new Date('2024-04-05'),
    updatedAt: new Date('2024-04-10'),
  },
  {
    id: 'lead-003',
    indicacaoId: 'ind-003',
    indicacao: indicacoes[2],
    comercialId: 'com-1',
    comercial: comerciais[0],
    status: 'novo',
    observacoes: [],
    createdAt: new Date('2024-04-20'),
    updatedAt: new Date('2024-04-20'),
  },
  {
    id: 'lead-004',
    indicacaoId: 'ind-006',
    indicacao: indicacoes[5],
    comercialId: 'com-1',
    comercial: comerciais[0],
    status: 'em_atendimento',
    primeiroContato: new Date('2024-04-18T09:15:00'),
    ultimoContato: new Date('2024-04-22T16:45:00'),
    observacoes: ['Primeiro contato realizado', 'Cliente solicitou proposta formal'],
    createdAt: new Date('2024-04-18'),
    updatedAt: new Date('2024-04-22'),
  },
  {
    id: 'lead-005',
    indicacaoId: 'ind-005',
    indicacao: indicacoes[4],
    comercialId: 'com-3',
    comercial: comerciais[2],
    status: 'perdido',
    primeiroContato: new Date('2024-02-15T11:00:00'),
    ultimoContato: new Date('2024-02-28T14:30:00'),
    observacoes: ['Cliente não atendeu várias vezes', 'Lead encerrado por falta de interesse'],
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2024-03-01'),
  },
  {
    id: 'lead-006',
    indicacaoId: 'ind-004',
    indicacao: indicacoes[3],
    comercialId: 'com-1',
    comercial: comerciais[0],
    status: 'vendido',
    primeiroContato: new Date('2024-03-01T10:00:00'),
    ultimoContato: new Date('2024-03-15T17:00:00'),
    observacoes: ['Venda fechada', 'Instalação agendada'],
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-03-20'),
  },
]

// Pagamentos
export const pagamentos: Pagamento[] = [
  {
    id: 'pag-001',
    indicadorId: 'ind-1',
    indicador: indicadores[0],
    indicacaoId: 'ind-001',
    indicacao: indicacoes[0],
    valor: 129.90,
    tipo: 'pix',
    status: 'pago',
    dataVencimento: new Date('2024-03-30'),
    dataPagamento: new Date('2024-03-30'),
    comprovanteUrl: '/comprovantes/pag-001.pdf',
    createdAt: new Date('2024-03-25'),
  },
  {
    id: 'pag-002',
    indicadorId: 'ind-2',
    indicador: indicadores[1],
    indicacaoId: 'ind-004',
    indicacao: indicacoes[3],
    valor: 159.90,
    tipo: 'pix',
    status: 'pendente',
    dataVencimento: new Date('2024-04-30'),
    createdAt: new Date('2024-03-20'),
  },
  {
    id: 'pag-003',
    indicadorId: 'ind-5',
    indicador: indicadores[4],
    indicacaoId: 'ind-007',
    indicacao: indicacoes[6],
    valor: 99.90,
    tipo: 'pix',
    status: 'pago',
    dataVencimento: new Date('2024-03-15'),
    dataPagamento: new Date('2024-03-15'),
    comprovanteUrl: '/comprovantes/pag-003.pdf',
    createdAt: new Date('2024-02-28'),
  },
  {
    id: 'pag-004',
    indicadorId: 'ind-1',
    indicador: indicadores[0],
    indicacaoId: 'ind-002',
    indicacao: indicacoes[1],
    valor: 99.90,
    tipo: 'desconto_fatura',
    status: 'pendente',
    dataVencimento: new Date('2024-05-15'),
    createdAt: new Date('2024-04-10'),
  },
]

// Histórico
export const historicos: Historico[] = [
  {
    id: 'hist-001',
    leadId: 'lead-001',
    comercialId: 'com-1',
    comercial: comerciais[0],
    acao: 'Primeiro Contato',
    descricao: 'Ligação realizada, cliente demonstrou interesse no plano Tanto 400.',
    createdAt: new Date('2024-03-10T10:30:00'),
  },
  {
    id: 'hist-002',
    leadId: 'lead-001',
    comercialId: 'com-1',
    comercial: comerciais[0],
    acao: 'Visita Agendada',
    descricao: 'Agendada visita técnica para verificar viabilidade.',
    createdAt: new Date('2024-03-12T14:00:00'),
  },
  {
    id: 'hist-003',
    leadId: 'lead-001',
    comercialId: 'com-1',
    comercial: comerciais[0],
    acao: 'Venda Fechada',
    descricao: 'Cliente assinou contrato do plano Tanto 400. Instalação agendada.',
    createdAt: new Date('2024-03-20T15:00:00'),
  },
  {
    id: 'hist-004',
    leadId: 'lead-002',
    comercialId: 'com-2',
    comercial: comerciais[1],
    acao: 'Primeiro Contato',
    descricao: 'Enviado WhatsApp, cliente solicitou mais informações sobre os planos.',
    createdAt: new Date('2024-04-05T14:00:00'),
  },
  {
    id: 'hist-005',
    leadId: 'lead-002',
    comercialId: 'com-2',
    comercial: comerciais[1],
    acao: 'Proposta Enviada',
    descricao: 'Enviado comparativo de planos por e-mail. Aguardando retorno.',
    createdAt: new Date('2024-04-10T11:30:00'),
  },
]

// Dashboard Indicador
export const dashboardIndicador: DashboardIndicador = {
  totalIndicacoes: 25,
  emAndamento: 3,
  aprovadas: 18,
  recusadas: 4,
  totalRecebido: 1798.20,
  totalAReceber: 329.70,
  saldoDisponivel: 299.70,
  saldoEmDesconto: 99.90,
}

// Dashboard Comercial
export const dashboardComercial: DashboardComercial = {
  leadsNovos: 5,
  leadsEmAtendimento: 8,
  leadsSemContato: 2,
  leadsEmNegociacao: 4,
  vendasRealizadas: 87,
  leadsPerdidos: 12,
  tempoMedioPrimeiroContato: '8 min',
}

// Dashboard Admin
export const dashboardAdmin: DashboardAdmin = {
  totalIndicacoes: 157,
  novasIndicacoes: 12,
  leadsSemContato: 3,
  leadsRedistribuidos: 2,
  indicacoesAprovadas: 126,
  recompensasPendentes: 15,
  totalPago: 12590.30,
  totalAPagar: 2345.60,
  conversaoPorIndicacao: 80.25,
  rankingIndicadores: [
    { indicador: indicadores[4], indicacoes: 67, aprovadas: 58 },
    { indicador: indicadores[1], indicacoes: 42, aprovadas: 35 },
    { indicador: indicadores[0], indicacoes: 25, aprovadas: 18 },
    { indicador: indicadores[2], indicacoes: 15, aprovadas: 10 },
    { indicador: indicadores[3], indicacoes: 8, aprovadas: 5 },
  ],
  rankingComerciais: [
    { comercial: comerciais[1], vendas: 112, tempoMedio: '5 min' },
    { comercial: comerciais[3], vendas: 94, tempoMedio: '7 min' },
    { comercial: comerciais[0], vendas: 87, tempoMedio: '8 min' },
    { comercial: comerciais[2], vendas: 65, tempoMedio: '12 min' },
  ],
}

// Current logged user (for demo)
export const currentIndicador = indicadores[0]
export const currentComercial = comerciais[0]
export const currentAdmin = admins[0]
